# Generated by Django 4.1.5 on 2023-01-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HackUser",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="registered",
        ),
    ]
