# Generated by Django 4.1.5 on 2023-01-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_hackuser_blocked_remove_hackuser_following_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackuser",
            name="modified_time",
            field=models.CharField(default="01/21/2023 04:12:44 PM", max_length=50),
        ),
    ]
