# Generated by Django 4.1.5 on 2023-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_hackuser_modified_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackuser",
            name="modified_time",
            field=models.CharField(default="01/21/2023 04:20:20 PM", max_length=50),
        ),
    ]
