# Generated by Django 4.1.5 on 2023-01-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_hackuser_modified_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackuser",
            name="modified_time",
            field=models.CharField(default="01/21/2023 04:50:29 PM", max_length=50),
        ),
    ]
