# Generated by Django 4.1.5 on 2023-01-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_hackuser_modified_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackuser",
            name="modified_time",
            field=models.CharField(default="01/21/2023 05:16:55 PM", max_length=50),
        ),
    ]
