# Generated by Django 4.1.5 on 2023-01-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_hackuser_options_alter_hackuser_modified_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hackuser",
            options={"ordering": ("-id",)},
        ),
        migrations.RenameField(
            model_name="hackuser",
            old_name="country",
            new_name="company",
        ),
        migrations.AddField(
            model_name="hackuser",
            name="position",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hackuser",
            name="modified_time",
            field=models.CharField(default="01/21/2023 08:46:50 PM", max_length=50),
        ),
    ]
