# Generated by Django 4.1.5 on 2023-01-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_hackuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackuser",
            name="modified_time",
            field=models.CharField(default="01/21/2023 08:46:55 PM", max_length=50),
        ),
    ]
