# Generated by Django 4.1.5 on 2023-01-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_hackuser_modified_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackuser",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hackuser",
            name="company",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hackuser",
            name="modified_time",
            field=models.CharField(default="01/21/2023 08:48:52 PM", max_length=50),
        ),
        migrations.AlterField(
            model_name="hackuser",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
