# Generated by Django 4.1.5 on 2023-01-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_remove_hackuser_modified_time_hackuser_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackuser",
            name="registered",
            field=models.CharField(default="01/21/2023 09:21:40 PM", max_length=50),
        ),
    ]
