# Generated by Django 4.1.5 on 2023-01-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_hackuser_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackuser",
            name="registered",
            field=models.CharField(
                blank=True, default="01/21/2023 09:25:36 PM", max_length=50
            ),
        ),
    ]
