# Generated by Django 4.1.5 on 2023-01-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_alter_hackuser_registered"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackuser",
            name="email",
            field=models.EmailField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="hackuser",
            name="registered",
            field=models.CharField(
                blank=True, default="01/21/2023 10:20:51 PM", max_length=50
            ),
        ),
    ]
