# Generated by Django 4.1.5 on 2023-01-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_hackuser_email_alter_hackuser_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackuser",
            name="registered",
            field=models.CharField(
                blank=True, default="01/22/2023 12:42:21 PM", max_length=50
            ),
        ),
    ]
