# Generated by Django 4.1.5 on 2023-01-22 11:20

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_alter_hackuser_registered"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hackuser",
            old_name="company",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="hackuser",
            name="position",
        ),
        migrations.AddField(
            model_name="hackuser",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="hackuser",
            name="registered",
            field=models.CharField(
                blank=True, default="01/22/2023 01:20:28 PM", max_length=50
            ),
        ),
    ]
