# Generated by Django 4.1.5 on 2023-01-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_company_user_likes_user_posts_user_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(default="k1.png", upload_to="media/"),
        ),
    ]
