# Generated by Django 4.1.5 on 2023-01-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
    ]
