# Generated by Django 4.1.5 on 2023-01-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(default="k1.png", upload_to="media/"),
        ),
    ]
