# Generated by Django 4.1.5 on 2023-01-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HackPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000, null=True)),
                (
                    "timestamp",
                    models.CharField(
                        blank=True, default="01/22/2023 03:24:04 PM", max_length=50
                    ),
                ),
                ("likes", models.IntegerField(default=0)),
                ("published", models.BooleanField(default=True)),
            ],
        ),
    ]
