# Generated by Django 4.1.5 on 2023-01-23 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HackPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=1000, null=True)),
                ("likes", models.IntegerField(default=0)),
                ("published", models.BooleanField(default=True)),
                ("posted_on", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Post",
            },
        ),
    ]
