# Generated by Django 4.1.5 on 2023-01-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hacktweets",
            name="time",
            field=models.CharField(default="01/21/2023 01:02:08 PM", max_length=50),
        ),
    ]
