# Generated by Django 4.1.5 on 2023-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0005_hackpost_delete_hacktweets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hackpost",
            old_name="like",
            new_name="liked_by",
        ),
        migrations.RemoveField(
            model_name="hackpost",
            name="time",
        ),
        migrations.AddField(
            model_name="hackpost",
            name="timestamp",
            field=models.CharField(default="01/21/2023 04:20:20 PM", max_length=50),
        ),
    ]
