# Generated by Django 4.1.5 on 2023-01-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0006_rename_like_hackpost_liked_by_remove_hackpost_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackpost",
            name="timestamp",
            field=models.CharField(default="01/21/2023 04:37:55 PM", max_length=50),
        ),
    ]
