# Generated by Django 4.1.5 on 2023-01-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0009_alter_hackpost_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackpost",
            name="removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="hackpost",
            name="timestamp",
            field=models.CharField(default="01/21/2023 05:08:34 PM", max_length=50),
        ),
    ]
