# Generated by Django 4.1.5 on 2023-01-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0011_alter_hackpost_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hackpost",
            name="removed",
        ),
        migrations.AddField(
            model_name="hackpost",
            name="published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="hackpost",
            name="timestamp",
            field=models.CharField(default="01/21/2023 05:26:32 PM", max_length=50),
        ),
    ]
