# Generated by Django 4.1.5 on 2023-01-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_hackuser_modified_time"),
        ("tweets", "0012_remove_hackpost_removed_hackpost_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackpost",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_users", to="users.hackuser"
            ),
        ),
        migrations.AlterField(
            model_name="hackpost",
            name="timestamp",
            field=models.CharField(default="01/21/2023 08:31:39 PM", max_length=50),
        ),
    ]
