# Generated by Django 4.1.5 on 2023-01-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0017_alter_hackpost_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackpost",
            name="timestamp",
            field=models.CharField(default="01/21/2023 08:49:59 PM", max_length=50),
        ),
    ]
