# Generated by Django 4.1.5 on 2023-01-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0018_alter_hackpost_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackpost",
            name="content",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="hackpost",
            name="timestamp",
            field=models.CharField(default="01/21/2023 09:21:40 PM", max_length=50),
        ),
    ]
