# Generated by Django 4.1.5 on 2023-01-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0019_alter_hackpost_content_alter_hackpost_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackpost",
            name="timestamp",
            field=models.CharField(
                blank=True, default="01/21/2023 09:22:29 PM", max_length=50
            ),
        ),
    ]
