# Generated by Django 4.1.5 on 2023-01-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_hackuser_registered"),
        ("tweets", "0020_alter_hackpost_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackpost",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True,
                default="No likes",
                related_name="liked_users",
                to="users.hackuser",
            ),
        ),
        migrations.AlterField(
            model_name="hackpost",
            name="timestamp",
            field=models.CharField(
                blank=True, default="01/21/2023 09:25:36 PM", max_length=50
            ),
        ),
    ]
