# Generated by Django 4.1.5 on 2023-01-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0023_alter_hackpost_liked_by_alter_hackpost_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackpost",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="hackpost",
            name="timestamp",
            field=models.CharField(
                blank=True, default="01/21/2023 09:29:37 PM", max_length=50
            ),
        ),
    ]
