# Generated by Django 4.1.5 on 2023-01-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0024_hackpost_likes_alter_hackpost_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackpost",
            name="timestamp",
            field=models.CharField(
                blank=True, default="01/21/2023 10:19:01 PM", max_length=50
            ),
        ),
    ]
