# Generated by Django 4.1.5 on 2023-01-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0029_alter_hackpost_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackpost",
            name="timestamp",
            field=models.CharField(
                blank=True, default="01/22/2023 01:20:28 PM", max_length=50
            ),
        ),
    ]
